server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://htnbyfeivrrugf:8aa1c3efb1e2e701f62455333c5a19e599d53e856a47c43e8b3f5de921e6d814@ec2-52-23-45-36.compute-1.amazonaws.com:5432/d8anp36e6pni4f #jdbc:postgresql://localhost:4000/bootcamp
    username: htnbyfeivrrugf #postgres
    password: 8aa1c3efb1e2e701f62455333c5a19e599d53e856a47c43e8b3f5de921e6d814 #123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Santander